In [1]:
import numpy as np 
import pandas as pd

In [3]:
my_list=[1,2,3]
print("type", type(my_list))
print(my_list)

type <class 'list'>
[1, 2, 3]


In [6]:
np.array(my_list)

array([1, 2, 3])

In [11]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.rand(3,3)

array([[0.66146619, 0.27087788, 0.20753431],
       [0.29013014, 0.33016604, 0.72569523],
       [0.58124498, 0.05559247, 0.87034848]])

In [26]:
np.random.randn(3,3)

array([[ 0.17142532, -0.75310527, -0.30289345],
       [-1.51098006, -0.24567076, -0.95728428],
       [-1.33559215, -0.86184957,  2.23009681]])

In [34]:
np.random.randint(0,100,4)

array([ 1,  9, 88, 32])

In [48]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [56]:
arr.shape

(5,)

In [55]:
arr.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [51]:
arr.reshape(1,5).shape

(1, 5)

In [ ]:
print(arr.dtype)

In [61]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [62]:
np.exp(arr)
#e power num

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [69]:
print(arr[:-1])

[0 1 2 3]


In [74]:
arr=np.arange(0,5)

In [75]:
#static....... 
slice=arr[3:5]

In [84]:
print(slice)

[  3 100]


In [85]:
slice[1]=100

In [82]:
arr

array([  0,   1,   2,   3, 100])

In [83]:
slice=arr[3:5].copy()

In [86]:
arr

array([  0,   1,   2,   3, 100])

In [89]:
arr=np.array([[[1,2],[3,4]],[[4,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
4
6
7
8


In [94]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}

In [95]:
print(d)

{'a': 10, 'b': 20, 'c': 30}
